### ISSUE TITLE
Issue Report: MQTT 5 Feature Support and Compatibility in FlashMQ

### ISSUE THREAD

**Issue by bot973** [halfgaar/FlashMQ#122] opened 2024-11-05 07:50 UTC
**Description:**
While working with FlashMQ for various MQTT 5 features, we encountered several issues related to the implementation and compatibility of certain MQTT 5 functionalities. These issues include Topic Alias mapping, Will Message behavior, QoS 2 message handling, Correlation Data in request-response, and message expiry handling. Below are the specific details of each behavior we observed.
**Configuration:**
```
log_file: FlashMQ/build/flashmq.log
storage_dir: FlashMQ/build
thread_count: 8
allow_anonymous: true
```
**MQTT Protocol Version:** 5

**1. Issue: MQTT v5 Topic Alias Not Working as Expected in FlashMQ**
**Description:** While using the MQTT v5 Topic Alias feature, Topic Alias=2 was initially set in the first PUBLISH packet from the publisher to establish an alias-to-topic mapping for the topic "alias". After this alias was set, a subsequent PUBLISH packet was sent using Topic Alias=2 without specifying the topic name, expecting the broker to map this alias to the original topic "alias". However, the subscriber did not receive the expected Publish Message, indicating that the broker might not be applying the Topic Alias mapping correctly.

**Observation:** The subscriber did not receive any Publish Message, suggesting that the broker may not support or correctly implement the Topic Alias feature. Are there any specific configurations or details we should be aware of to enable this behavior?
[issue1-topic-alias-flashmq.zip](https://github.com/user-attachments/files/17627917/issue1-topic-alias-flashmq.zip)

**2. Issue: MQTT Subscribe Request Not Receiving SubAck and No Subsequent Publish Messages**
**Description:**  In this scenario, a client sends a Subscribe Request but does not receive a SubAck from the broker. As a result, no Publish messages are received either, leading to an abnormal disconnect on the client side. This behavior was observed while verifying the broker’s handling of MQTT v5 message expiry intervals on will message republishing.

**Steps to Reproduce:**

 1. Configure the broker with the above configuration.
 2. The client connects with clean_session=False and subscribes to the topic with QoS=1.
 3. The client disconnects after subscribing.
 4. A helper client publishes two messages to the topic, one with a short expiry interval (10 seconds) and another with a longer expiry.
The client reconnects, expecting to receive the long expiry message with a reduced expiry interval.

**Observed Behavior:** The client successfully sends a Subscribe Request but does not receive a SubAck from the broker.
Without receiving the SubAck, no Publish messages are sent to the client.
Eventually, the client sends a Disconnect request after waiting for a response that never arrives.

**Expected Behavior:**  After the Subscribe Request, the broker should respond with a SubAck, and upon reconnection, the client should receive the  will message from the helper client with a progressively reduced expiry interval.
[issue2-qos1-expiry-will-flashmq.zip](https://github.com/user-attachments/files/17628237/issue2-qos1-expiry-will-flashmq.zip)

**3. Issue: Unexpected Disconnection After Consecutive QoS 2 Publish Messages**
**Description:** When sending two consecutive QoS 2 PUBLISH messages with different Packet Identifiers (e.g., id=102 and id=1) but the same topic, the broker disconnects unexpectedly after the second message. The first message completes the full QoS 2 handshake (PUBLISH → PUBREC → PUBREL → PUBCOMP) successfully. However, the broker disconnects immediately after receiving the second message, without completing the handshake process.

**Expected Behavior:** Each QoS 2 PUBLISH message should independently complete the four-step handshake, allowing continuous operation without disconnection.

**Question:** Could you kindly confirm if this behavior is expected in FlashMQ?
[issue3-qos2-flashmq.zip](https://github.com/user-attachments/files/17628411/issue3-qos2-flashmq.zip)

**4. Issue: Unexpected Will Message Delivery on Reconnection with Clean Session**
**Description:**  In an MQTT 5 setup with a will delay interval configured, a client reconnects with Clean Session = True after previously connecting with a will message on a specified topic. The expectation is that the client should not receive the will message upon reconnecting, as the clean session should effectively remove the will settings. However, we observed that the broker still delivers the will message to the client.
[issue4.zip](https://github.com/user-attachments/files/17628564/issue4.zip)

**Steps to Reproduce:**
 1. The first client connects with a persistent session and subscribes to the topic where the will message will be published.
 2. A second client connects with clean_session=False, sets a will message on the topic, and then disconnects.
 3. The second client reconnects with clean_session=True and without a will message, then disconnects again.
 
**Question:** Could you confirm if the broker fully supports clean session handling in this context? If there is any specific configuration required to ensure will messages are cleared on reconnection with Clean Session = True, please advise.

**5. Issue: Correlation Data Property Not Applied in Response Message**
**Description:**  In implementing an MQTT 5 request-response pattern between two clients, we encountered an issue with the Response Topic and Correlation Data properties. The goal was to use Correlation Data to uniquely identify responses that correspond to specific requests. However, the Correlation Data property was not present in the response message, making it difficult to confirm the correspondence between request and response.

**Steps to Reproduce:**
 1. Client 1 subscribes to normal/topic, and Client 2 subscribes to response/topic.
 2. Client 2 publishes a message to normal/topic with the following properties:

    - Response Topic: response/topic
    - Correlation Data: "abcd234"

 3. Client 1 receives the message on normal/topic and publishes a response to response/topic.
 4. Client 2 expects to receive the response on response/topic with the original Correlation Data included to verify correspondence with the initial request.

**Observed Behavior:**  The response message was published on response/topic, but the Correlation Data property was missing, making it challenging to match the response to the original request.

**Question:** Could you kindly confirm if the Response Topic and Correlation Data properties are fully supported in FlashMQ for such request-response scenarios? If specific configurations are required to enable or properly handle these properties, we would appreciate any guidance.
[issue5.zip](https://github.com/user-attachments/files/17628831/issue5.zip)

-------------------------------------------------------------------------------------------------------------------------------------------------
These issues suggest potential configuration or compatibility concerns related to MQTT 5 feature support in FlashMQ. We apologize if this inquiry requires additional effort on your end, and we would be grateful for any guidance or clarification regarding the expected behavior for these features.

Thank you very much for your time and assistance in addressing these observations.

**Comment by halfgaar** [comment] 2024-11-05 08:19
MQTT5 is supported. Some of these are surprising to say the least. Can you include the flashmq log output for each of these events?

**Comment by halfgaar** [comment] 2024-11-05 19:56
Some of what you describe seems to be caused by a recent commit: https://github.com/halfgaar/FlashMQ/commit/c2fc2f6293f0b4bf70cf81b2cc15dca5c72a5b22

A fix has been pushed to master: https://github.com/halfgaar/FlashMQ/commit/d1f366fc8905f2e83b39509bbe443b74ec53849c

New patch release is underway.

Can you retry some stuff with the current master branch?

**Comment by bot973** [comment] 2024-11-06 03:10
Thank you for your response. 
I will re-verify the issues and record the logs as suggested. I will check the results with the current master branch.

**Comment by bot973** [comment] 2024-11-06 05:35
During my recent round of validation, I am pleased to report that Issue 4 has been effectively resolved.
I have recorded the logs for Issue 1 2 3 5, as detailed below:
Issue 1:
```
[INFO] [main] Setting rlimit nofile to 1000000
[ERROR] [main] Setting ulimit nofile failed: 'Operation not permitted'. This means the default is used. Note. It's also subject to systemd's 'LimitNOFILE', which in turn is maxed to '/proc/sys/fs/nr_open', which can be set like 'sysctl fs.nr_open=15000000'
[NOTICE] [main] 8 threads specified by 'thread_count'.
[NOTICE] [main] Loading 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Loading 'flashmq-d1f366f/build/sessions.db'
[NOTICE] [main] Starting FlashMQ version 1.17.2, release build with SSE4.2 support.
[INFO] [main] Switching logging from stdout to logfile 'flashmq-d1f366f/logs/issue1.log'
[NOTICE] [T 0] Thread 0 doing auth init.
[NOTICE] [T 1] Thread 1 doing auth init.
[NOTICE] [T 2] Thread 2 doing auth init.
[NOTICE] [T 3] Thread 3 doing auth init.
[NOTICE] [T 4] Thread 4 doing auth init.
[NOTICE] [T 5] Thread 5 doing auth init.
[NOTICE] [T 6] Thread 6 doing auth init.
[NOTICE] [T 7] Thread 7 doing auth init.
[NOTICE] [main] Accepting connection from: address='127.0.0.1', transport='TCP/Non-SSL', fd=35
[NOTICE] [T 0] Client '[ClientID='sub-test', username='', fd=35, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]' logged in successfully
[NOTICE] [main] Accepting connection from: address='127.0.0.1', transport='TCP/Non-SSL', fd=36
[NOTICE] [T 1] Client '[ClientID='pub-test', username='', fd=36, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]' logged in successfully
[NOTICE] [T 0] Removing client '[ClientID='sub-test', username='', fd=35, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): Hang up, Connection reset by peer
[NOTICE] [T 1] Removing client '[ClientID='pub-test', username='', fd=36, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): socket disconnect detected
[NOTICE] [main] Quitting FlashMQ
[NOTICE] [T 3] Thread 3 doing auth cleanup.
[NOTICE] [T 5] Thread 5 doing auth cleanup.
[NOTICE] [T 7] Thread 7 doing auth cleanup.
[NOTICE] [T 0] Thread 0 doing auth cleanup.
[NOTICE] [T 6] Thread 6 doing auth cleanup.
[NOTICE] [T 2] Thread 2 doing auth cleanup.
[NOTICE] [T 4] Thread 4 doing auth cleanup.
[NOTICE] [T 1] Thread 1 doing auth cleanup.
[NOTICE] [main] Saving retained messages to 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Saving sessions and subscriptions to 'flashmq-d1f366f/build/sessions.db' in thread.
[INFO] [main] Collected 0 sessions and 0 subscriptions to save, in 0 ms (including defer time).
[INFO] [main] Saved 0 sessions and 0 subscriptions to 'flashmq-d1f366f/build/sessions.db', in 0 ms.
[NOTICE] [main] Saving bridge info in 'flashmq-d1f366f/build/bridgenames.db'
[NOTICE] [main] Saving states done
```
Issue 2:
```
[INFO] [main] Setting rlimit nofile to 1000000
[ERROR] [main] Setting ulimit nofile failed: 'Operation not permitted'. This means the default is used. Note. It's also subject to systemd's 'LimitNOFILE', which in turn is maxed to '/proc/sys/fs/nr_open', which can be set like 'sysctl fs.nr_open=15000000'
[NOTICE] [main] 8 threads specified by 'thread_count'.
[NOTICE] [main] Loading 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Loading 'flashmq-d1f366f/build/sessions.db'
[NOTICE] [main] Starting FlashMQ version 1.17.2, release build with SSE4.2 support.
[INFO] [main] Switching logging from stdout to logfile 'flashmq-d1f366f/logs/issue2.log'
[NOTICE] [T 0] Thread 0 doing auth init.
[NOTICE] [T 1] Thread 1 doing auth init.
[NOTICE] [T 2] Thread 2 doing auth init.
[NOTICE] [T 4] Thread 4 doing auth init.
[NOTICE] [T 3] Thread 3 doing auth init.
[NOTICE] [T 5] Thread 5 doing auth init.
[NOTICE] [T 6] Thread 6 doing auth init.
[NOTICE] [T 7] Thread 7 doing auth init.
[NOTICE] [main] Accepting connection from: address='127.0.0.1', transport='TCP/Non-SSL', fd=35
[NOTICE] [T 0] Client '[ClientID='subpub-qos0-test', username='', fd=35, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=0]' logged in successfully
[ERROR] [T 0] Packet read/write error: Connection reset by peer. Removing client [ClientID='subpub-qos0-test', username='', fd=35, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=0]
[NOTICE] [T 0] Removing client '[ClientID='subpub-qos0-test', username='', fd=35, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=0]'. Reason(s): Connection reset by peer
[NOTICE] [main] Quitting FlashMQ
[NOTICE] [T 1] Thread 1 doing auth cleanup.
[NOTICE] [T 2] Thread 2 doing auth cleanup.
[NOTICE] [T 6] Thread 6 doing auth cleanup.
[NOTICE] [T 4] Thread 4 doing auth cleanup.
[NOTICE] [T 3] Thread 3 doing auth cleanup.
[NOTICE] [T 7] Thread 7 doing auth cleanup.
[NOTICE] [T 0] Thread 0 doing auth cleanup.
[NOTICE] [T 5] Thread 5 doing auth cleanup.
[NOTICE] [main] Saving retained messages to 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Saving sessions and subscriptions to 'flashmq-d1f366f/build/sessions.db' in thread.
[INFO] [main] Collected 1 sessions and 0 subscriptions to save, in 0 ms (including defer time).
[INFO] [main] Saved 1 sessions and 0 subscriptions to 'flashmq-d1f366f/build/sessions.db', in 0 ms.
[NOTICE] [main] Saving bridge info in 'flashmq-d1f366f/build/bridgenames.db'
[NOTICE] [main] Saving states done
```
Issue 3:
```
[INFO] [main] Setting rlimit nofile to 1000000
[ERROR] [main] Setting ulimit nofile failed: 'Operation not permitted'. This means the default is used. Note. It's also subject to systemd's 'LimitNOFILE', which in turn is maxed to '/proc/sys/fs/nr_open', which can be set like 'sysctl fs.nr_open=15000000'
[NOTICE] [main] 8 threads specified by 'thread_count'.
[NOTICE] [main] Loading 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Loading 'flashmq-d1f366f/build/sessions.db'
[NOTICE] [main] Starting FlashMQ version 1.17.2, release build with SSE4.2 support.
[INFO] [main] Switching logging from stdout to logfile 'flashmq-d1f366f/logs/issue3.log'
[NOTICE] [T 0] Thread 0 doing auth init.
[NOTICE] [T 1] Thread 1 doing auth init.
[NOTICE] [T 2] Thread 2 doing auth init.
[NOTICE] [T 3] Thread 3 doing auth init.
[NOTICE] [T 4] Thread 4 doing auth init.
[NOTICE] [T 5] Thread 5 doing auth init.
[NOTICE] [T 6] Thread 6 doing auth init.
[NOTICE] [T 7] Thread 7 doing auth init.
[NOTICE] [main] Accepting connection from: address='127.0.0.1', transport='TCP/Non-SSL', fd=35
[NOTICE] [T 0] Client '[ClientID='subpub-qos2', username='', fd=35, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]' logged in successfully
[NOTICE] [main] Quitting FlashMQ
[NOTICE] [T 2] Thread 2 doing auth cleanup.
[NOTICE] [T 5] Thread 5 doing auth cleanup.
[NOTICE] [T 1] Thread 1 doing auth cleanup.
[NOTICE] [T 3] Thread 3 doing auth cleanup.
[NOTICE] [T 6] Thread 6 doing auth cleanup.
[NOTICE] [T 7] Thread 7 doing auth cleanup.
[NOTICE] [T 4] Thread 4 doing auth cleanup.
[NOTICE] [T 0] Removing client '[ClientID='subpub-qos2', username='', fd=35, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): Server initiating disconnect with reason: ServerShuttingDown
[NOTICE] [T 0] Thread 0 doing auth cleanup.
[NOTICE] [main] Saving retained messages to 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Saving sessions and subscriptions to 'flashmq-d1f366f/build/sessions.db' in thread.
[INFO] [main] Collected 1 sessions and 0 subscriptions to save, in 0 ms (including defer time).
[INFO] [main] Saved 1 sessions and 0 subscriptions to 'flashmq-d1f366f/build/sessions.db', in 0 ms.
[NOTICE] [main] Saving bridge info in 'flashmq-d1f366f/build/bridgenames.db'
[NOTICE] [main] Saving states done
```
Issue 5:
```
[INFO] [main] Setting rlimit nofile to 1000000
[ERROR] [main] Setting ulimit nofile failed: 'Operation not permitted'. This means the default is used. Note. It's also subject to systemd's 'LimitNOFILE', which in turn is maxed to '/proc/sys/fs/nr_open', which can be set like 'sysctl fs.nr_open=15000000'
[NOTICE] [main] 8 threads specified by 'thread_count'.
[NOTICE] [main] Loading 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Loading 'flashmq-d1f366f/build/sessions.db'
[NOTICE] [main] Starting FlashMQ version 1.17.2, release build with SSE4.2 support.
[INFO] [main] Switching logging from stdout to logfile 'flashmq-d1f366f/logs/issue5.log'
[NOTICE] [T 0] Thread 0 doing auth init.
[NOTICE] [T 1] Thread 1 doing auth init.
[NOTICE] [T 2] Thread 2 doing auth init.
[NOTICE] [T 3] Thread 3 doing auth init.
[NOTICE] [T 4] Thread 4 doing auth init.
[NOTICE] [T 5] Thread 5 doing auth init.
[NOTICE] [T 6] Thread 6 doing auth init.
[NOTICE] [T 7] Thread 7 doing auth init.
[NOTICE] [main] Accepting connection from: address='127.0.0.1', transport='TCP/Non-SSL', fd=35
[NOTICE] [T 0] Client '[ClientID='client1', username='', fd=35, keepalive=10s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]' logged in successfully
[NOTICE] [main] Accepting connection from: address='127.0.0.1', transport='TCP/Non-SSL', fd=36
[NOTICE] [T 1] Client '[ClientID='client2', username='', fd=36, keepalive=10s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]' logged in successfully
[NOTICE] [main] Quitting FlashMQ
[NOTICE] [T 0] Removing client '[ClientID='client1', username='', fd=35, keepalive=10s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): socket disconnect detected
[NOTICE] [T 1] Removing client '[ClientID='client2', username='', fd=36, keepalive=10s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): socket disconnect detected
[NOTICE] [T 0] Thread 0 doing auth cleanup.
[NOTICE] [T 3] Thread 3 doing auth cleanup.
[NOTICE] [T 1] Thread 1 doing auth cleanup.
[NOTICE] [T 4] Thread 4 doing auth cleanup.
[NOTICE] [T 7] Thread 7 doing auth cleanup.
[NOTICE] [T 2] Thread 2 doing auth cleanup.
[NOTICE] [T 6] Thread 6 doing auth cleanup.
[NOTICE] [T 5] Thread 5 doing auth cleanup.
[NOTICE] [main] Saving retained messages to 'flashmq-d1f366f/build/retained.db'
[NOTICE] [main] Saving sessions and subscriptions to 'flashmq-d1f366f/build/sessions.db' in thread.
[INFO] [main] Collected 0 sessions and 0 subscriptions to save, in 0 ms (including defer time).
[INFO] [main] Saved 0 sessions and 0 subscriptions to 'flashmq-d1f366f/build/sessions.db', in 0 ms.
[NOTICE] [main] Saving bridge info in 'flashmq-d1f366f/build/bridgenames.db'
[NOTICE] [main] Saving states done
```

**Comment by bot973** [comment] 2024-11-07 12:40
1. I am currently using the Mosquitto client.  Could this potentially lead to differences in packet sequence or response processing?
2. Regarding the construction of specific packets , I will include detailed information for each issue1 2 3 5, along with logs that include timestamps to clearly show the event sequence.
3. I am not an AI; I am an actual user.

**Comment by bot973** [comment] 2024-11-07 13:06
I have retested issue 3 and found that my script was incorrectly shutting down the broker prematurely. You were absolutely right about this. I will address the remaining three issues and hope to find solutions for them as well.

**Comment by bot973** [comment] 2024-11-08 08:03
I reconstructed the packets and verified them again, and the remaining issues were also resolved. Thank you very much for your help! I found that sometimes it's necessary to give flashmq more time to respond before closing the client's socket.

**Comment by halfgaar** [comment] 2024-11-09 14:52
Alright, I'll close the issue then.

**Closed by halfgaar** 2024-11-09 14:52 UTC
